INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Hanukkah', false, 1);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('6', false, 2);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Ron Weasley', false, 3);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Severus Snape', false, 3);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Red', true, 4);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('King Harvest', false, 5);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dragon', false, 6);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Venus', true, 8);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Herbert Hoover', false, 9);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dooms', false, 10);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Washington, D.C.', false, 11);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Marauder', false, 12);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('A bag of lemons', false, 13);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Louise', false, 14);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Paul', false, 15);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('O', false, 16);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Breakfast at Tiffanys', true, 17);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('A brain', false, 18);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Florida', false, 19);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Rachel', false, 20);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('206', true, 21);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Harry Styles', true, 22);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Zinc', false, 23);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Cobalt', false, 23);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('12', true, 24);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Chinese', true, 25);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1958', false, 26);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Macbeth', true, 27);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Chips Ahoy!', false, 28);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1', false, 29);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Shakespeare', false, 30);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Myspace', true, 31);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Bebo', true, 31);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Jupiter', true, 32);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Mercury', true, 32);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Red, yellow, green', false, 33);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('One Direction', false, 34);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Picasso', false, 35);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Washington', false, 36);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Indian', false, 37);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Empire State Building', false, 38);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Ernest', false, 39);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Germany', false, 40);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Van Gogh', false, 41);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Paris', false, 42);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Mona', false, 43);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('‘70s', false, 44);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Spain', false, 45);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Salt', true, 46);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pisces', false, 47);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('God tells her', false, 48);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('a student in Harry’s class', false, 49);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Facebook', true, 50);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Elton John', true, 51);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('0', false, 52);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Snow White', false, 53);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Princess Jasmin', false, 53);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Jesus’ entry into Jerusalem', true, 54);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Ron', false, 55);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('4', false, 56);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('hot water', false, 57);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('early spring', false, 58);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Amazon', false, 59);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('28', false, 60);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('360', true, 61);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Rome', false, 62);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('35', false, 63);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Charlie Baxter', false, 64);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('hair', false, 65);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Rome', false, 66);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Trump', true, 67);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Unidentified', true, 68);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Minnesota', false, 69);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Niall Horan', false, 70);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Snowboarding', false, 71);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('blue', false, 72);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Harry Potter', false, 73);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('serial killers', false, 74);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Trace Adkins', false, 75);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('7', true, 76);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pug', false, 77);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('J Cole', false, 78);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('5', false, 79);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pittsburgh', false, 80);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('France', false, 81);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('112', false, 82);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('D.C.', false, 83);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Brendan Urie', true, 84);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1910', false, 85);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('New Jersey', false, 86);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Lake Huron', true, 87);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('on Mars', false, 88);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Female Body Inspector', false, 89);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Python', false, 90);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('computer mouse', false, 91);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('only once', false, 92);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Squad', false, 93);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('86', false, 94);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pandora', false, 95);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Kid', true, 96);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('90', false, 97);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Toronto', true, 98);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Guggenheim', false, 99);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Bob’s Burgers', false, 100);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Law & Order', true, 101);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Belle', false, 102);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('every 7 days', false, 103);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pandora', false, 104);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('5', false, 105);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1,037', false, 106);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('North Wing', false, 107);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('32 degrees', true, 108);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Philadelphia', false, 109);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Harvard', true, 110);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Malibu', false, 111);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Sixth Sense', true, 112);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Bill Hader', false, 113);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Washington D.C.', false, 114);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Catcher in the Rye', false, 115);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Hedwig', true, 116);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Cinderella', false, 117);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Naked Brothers Band', false, 118);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('button-down shirt', false, 119);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Devil Wears Prada', false, 120);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Taming of the Shrew', true, 121);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Coney Island', true, 122);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('26', false, 123);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Neptune and Jupiter', false, 124);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Hungary', false, 125);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Audrey Hepburn', true, 126);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Robert Frost', false, 127);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('16', false, 128);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Lincoln', true, 129);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Kurt Vonnegut', true, 130);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('pumpkins', false, 131);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('lion', false, 132);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Lenny Kravitz', false, 133);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('7', false, 134);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Flight Plan', false, 135);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('5', true, 136);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Jasper Hale', false, 137);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('the day after Christmas', false, 138);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Buzz Aldrin', true, 139);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('8', true, 140);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Matthew', false, 141);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('John Hancock', true, 142);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Cinderella', false, 143);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('salt', false, 144);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dorney Park', false, 145);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('clothes', false, 146);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Washington, D.C.', false, 147);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Donald Glover', true, 148);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('water polo', false, 149);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('“Okay.”', false, 150);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Nintendo', true, 151);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Yom Kippur', false, 1);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('7', false, 2);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Neville Longbottom', false, 3);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Yellow', false, 4);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Spectrums', false, 5);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Rabbit', false, 6);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Ireland', false, 7);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Saturn', false, 8);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Richard Nixon', true, 9);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dark', false, 10);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Boston', false, 11);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Black Pearl', true, 12);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('A handful of roses', false, 13);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Gene', false, 14);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Callum', false, 15);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('A', false, 16);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pretty In Pink', false, 17);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('An oil can', false, 18);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('California', false, 19);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Joey', false, 20);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('205', false, 21);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dua Lipa', false, 22);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Hydrogen', false, 23);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('11', false, 24);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Spanish', false, 25);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1959', true, 26);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Hamlet', false, 27);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Milano', false, 28);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('2', false, 29);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Stephen King', false, 30);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Twitter', false, 31);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Saturn', false, 32);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Yellow, blue, green', false, 33);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Backstreet Boys', true, 34);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Da Vinci', false, 35);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Virginia', false, 36);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pacific', true, 37);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Bank of America Tower', false, 38);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Edward', false, 39);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('China', false, 40);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('da Vinci', true, 41);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Amsterdam', true, 42);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Charlie', false, 43);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('‘80s', true, 44);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Germany', false, 45);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Sugar', false, 46);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Aquarius', false, 47);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('the angel Gabriel tells her', true, 48);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('a professor at Hogwarts', false, 49);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Myspace', false, 50);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Phil Collins', false, 51);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1', false, 52);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pocahontas', true, 53);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Jesus’ resurrection', false, 54);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Snape', false, 55);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('5', true, 56);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('pavement/cement', false, 57);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('6 more weeks of winter', true, 58);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Congo', false, 59);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('29', true, 60);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('180', false, 61);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Barcelona', false, 62);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('32', true, 63);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Charlie Brown', false, 64);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('bushes', false, 65);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Budapest', true, 66);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Paris', true, 66);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Obama', false, 67);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Under', false, 68);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Iowa', false, 69);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Jaden Smith', false, 70);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Skiing', false, 71);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('yellow', false, 72);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Star Wars', true, 73);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('ghosts', false, 74);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Luke Bryan', true, 75);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('8', false, 76);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dalmatian', false, 77);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Post Malone', false, 78);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('6', true, 79);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Chicago', true, 80);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Hungary', false, 81);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('118', true, 82);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('NYC', true, 83);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Shawn Mendes', false, 84);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1920', true, 85);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Maine', false, 86);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Lake Hartwell', false, 87);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('on a spacecraft alone', false, 88);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Federal Bureau of Investigation', true, 89);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Cobra', false, 90);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('wallet', false, 91);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('3 times', false, 92);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pack', false, 93);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('87', false, 94);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Helen', false, 95);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Goatee', false, 96);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('103', false, 97);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Ontario', false, 98);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Louvre', true, 99);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Schitt’s Creek', true, 100);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Grey’s Anatomy', false, 101);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Cinderella', true, 102);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('every 27 days', true, 103);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Medusa', false, 104);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('6', true, 105);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('5,288', false, 106);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('South Wing', false, 107);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('40 degrees', false, 108);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pittsburgh', false, 109);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Yale', false, 110);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Huntington Beach', false, 111);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Grudge', false, 112);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Steve Jobs', false, 113);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('NYC', false, 114);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1984', false, 115);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Luna', false, 116);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Snow White', false, 117);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Jonas Brothers', true, 118);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('t-shirt', false, 119);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Les Miserables', true, 120);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Hamlet', false, 121);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Miami Beach', false, 122);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('27', true, 123);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Uranus and Pluto', false, 124);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Austria', false, 125);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Natalie Wood', false, 126);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Edgar Allen Poe', true, 127);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('24', true, 128);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Nixon', false, 129);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Stephen King', false, 130);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('beets', true, 131);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('cat', true, 132);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Eric Clapton', false, 133);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('24', true, 134);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Martian ', false, 135);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('7', false, 136);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Jacob Black', true, 137);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Harvest Day', false, 138);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Neil Armstrong', false, 139);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('9', false, 140);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Proverbs', false, 141);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Thomas Jefferson', false, 142);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Snow White and the Seven Dwarfs', true, 143);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('sugar', false, 144);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Walley World', true, 145);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('houses', false, 146);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Richmond', false, 147);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Will Smith', false, 148);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('swimming', false, 149);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('“Of course, I love you.”', false, 150);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Electronic Arts (EA)', false, 151);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Kwanza', false, 1);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('13', false, 2);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Draco Malfoy', true, 3);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Blue', false, 4);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Commodores', true, 5);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dog', false, 6);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Brazil', true, 7);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Mercury', false, 8);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('George W. Bush', false, 9);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Denmark ', false, 10);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Philadelphia', true, 11);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Black Python', false, 12);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('A lollipop', false, 13);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Jimmy', true, 14);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Kevin', false, 15);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('B', false, 16);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Funny Face', false, 17);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('A dog', false, 18);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Maine', false, 19);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Gunther', true, 20);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('201', false, 21);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Halsey', false, 22);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Fluorine', false, 23);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('10', false, 24);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Arabic', false, 25);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1956', false, 26);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Romeo & Juliet', false, 27);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Girl Scout Thin Mints', false, 28);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('3', true, 29);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Nathanial Hawthorne', true, 30);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Facebook', false, 31);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Neptune', false, 32);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Blue, green, red', true, 33);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('NSYNC', false, 34);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Michelangelo', true, 35);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Massachusetts', true, 36);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Atlantic', false, 37);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('One World Trade Center', true, 38);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Entertainment', true, 39);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('France', true, 40);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Picasso', false, 41);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Brussels', false, 42);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Alison', false, 43);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('‘90s', false, 44);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('North America', false, 45);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Chlorine', false, 46);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Cancer', true, 47);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('she has a dream about it', false, 48);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Harry’s birth father', false, 49);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Instagram', false, 50);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Celine Dion', false, 51);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('2', true, 52);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Elsa', false, 53);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Jesus feeding the thousands', false, 54);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dumbledore', true, 55);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('6', false, 56);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('rocks on fire', false, 57);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('it’s going to rain', false, 58);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Nile', true, 59);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('30', false, 60);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('150', false, 61);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('New York City', false, 62);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('30', false, 63);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Charlie Bones', false, 64);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('clothes', false, 65);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Barcelona', false, 66);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Bush', false, 67);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('United', false, 68);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pennsylvania', false, 69);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Shawn Mendes', false, 70);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Running', false, 71);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('red', true, 72);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Lord of the Rings', false, 73);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('aliens', true, 74);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Blake Shelton', false, 75);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('6', false, 76);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Beagle', false, 77);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Eminem', false, 78);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('7', false, 79);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('NYC', false, 80);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Scotland', true, 81);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('120', false, 82);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Philadelphia', false, 83);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Ellie Goulding', false, 84);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1930', false, 85);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('California', false, 86);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Lake Tahoe', false, 87);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('on the Moon', true, 88);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Federal Business of Investigation', false, 89);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Cobra', false, 90);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('stapler', true, 91);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('twice', false, 92);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Herd', false, 93);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('88', true, 94);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Cassiopeia', false, 95);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Child', false, 96);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('104', true, 97);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Quebec', false, 98);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Van Gogh museum', false, 99);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Parenthood', false, 100);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Criminal Minds', false, 101);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Jasmine', false, 102);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('every 30 days', false, 103);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Helen', false, 104);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('7', false, 105);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('5,280', true, 106);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('East Wing', false, 107);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('-10 degrees', false, 108);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Scranton', true, 109);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Columbia', false, 110);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('os Angeles', false, 111);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Shining', false, 112);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Bill Gates', true, 113);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Philadelphia', true, 114);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Outsiders', true, 115);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dobby', false, 116);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Sleeping Beauty', true, 117);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('One Direction', false, 118);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('turtleneck', true, 119);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Princess Diaries', false, 120);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Romeo and Juliet', false, 121);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Mall of America', false, 122);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('29', false, 123);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pluto and Jupiter', false, 124);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Czech Republic', true, 125);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Marilyn Monroe', false, 126);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Walt Whitman', false, 127);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('19', false, 128);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Jackson', false, 129);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('J.D. Salinger', false, 130);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('onions', false, 131);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('hummingbird', false, 132);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Bob Dylan', true, 133);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('23', false, 134);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Interstellar', true, 135);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('4', false, 136);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Billy Black', false, 137);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Boxing Day', true, 138);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Alan Bean', false, 139);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('10', false, 140);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Genesis', true, 141);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('John Adams', false, 142);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Sleeping Beauty', false, 143);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('baking soda', true, 144);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Six Flags', false, 145);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('books', true, 146);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Boston', false, 147);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Frank Ocean', false, 148);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('water skiing', false, 149);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('“As you wish.”', true, 150);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('SEGA', false, 151);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Rosh Hashanah', true, 1);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('0', true, 2);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Hermione Granger', false, 3);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('White', false, 4);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Marshall Tucker Band', false, 5);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Hummingbird', true, 6);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Italy', false, 7);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Mars', false, 8);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Barack Obama', false, 9);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dunkirk', true, 10);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Manhattan ', false, 11);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Slytherin', false, 12);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('A box of chocolates', true, 13);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Tina', false, 14);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Liam', true, 15);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('AB-Negative', true, 16);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Singing In The Rain', false, 17);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('A heart', true, 18);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Kansas', true, 19);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Monica', false, 20);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('209', false, 21);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Shawn Mendes', false, 22);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Iron', true, 23);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('15', false, 24);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('English', false, 25);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1961', false, 26);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Othello', false, 27);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Oreo', true, 28);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('4', false, 29);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Ernest Hemingway', false, 30);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Tumblr', false, 31);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Earth', false, 32);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Green, purple, orange', false, 33);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('New Kids On The Block', false, 34);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Van Gogh', false, 35);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pennsylvania', false, 36);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Arctic', false, 37);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Statue of Liberty', false, 38);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Extra', false, 39);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Italy', false, 40);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Monet', false, 41);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Frankfurt', false, 42);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Spencer', true, 43);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('early 2000s', false, 44);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Switzerland', true, 45);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Bleach', false, 46);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Virgo', false, 47);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('a doctor tells her', false, 48);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Voldemort', true, 49);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Twitter', false, 50);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Stevie Wonder', false, 51);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('3', false, 52);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Belle', false, 53);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Nothing, it just means to go to church on Sunday/the day of rest', false, 54);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('No one, he just finds it', false, 55);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('10', false, 56);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('a George Foreman Grill', true, 57);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('a tornado is coming', false, 58);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Hudson', false, 59);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('31', false, 60);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('359', false, 61);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Paris', true, 62);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('42', false, 63);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Charlie Bucket', true, 64);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('everything', true, 65);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Athens', false, 66);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Lincoln', false, 67);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Unique', false, 68);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Wisconsin', true, 69);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Justin Bieber', true, 70);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Swimming', true, 71);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('purple', false, 72);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Indiana Jones', false, 73);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('time travelers', false, 74);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Keith Urban', false, 75);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('10', false, 76);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Golden Retriever', true, 77);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Mac Miller', true, 78);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('8', false, 79);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('San Francisco', false, 80);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Austria', false, 81);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('143', false, 82);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Orlando', false, 83);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Halsey', false, 84);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('1940', false, 85);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Georgia', true, 86);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Great Bear Lake', false, 87);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('to travel to the sun', false, 88);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Federal Bureau of Inspection', false, 89);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Black Mamba', true, 90);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('coffee mug', false, 91);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('more than 3 times', true, 92);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pride', true, 93);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('89', false, 94);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Medusa', true, 95);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Baby Goat', false, 96);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('110', false, 97);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Vancouver', false, 98);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Metropolitan Museum of Art', false, 99);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('7th Heaven ', false, 100);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('NCIS', false, 101);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Sleeping Beauty', false, 102);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('every 365 days', false, 103);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Persephone', true, 104);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('8', false, 105);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('6,201', false, 106);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('West Wing', true, 107);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('0 degrees', false, 108);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Lancaster', false, 109);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('UCLA', false, 110);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Anaheim', true, 111);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Exorcist ', false, 112);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Mark Zuckerberg', false, 113);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Roanoke', false, 114);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Catch-22', false, 115);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Fluffy', false, 116);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Jasmine', false, 117);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('The Beatles', false, 118);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('blazer', false, 119);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Ella Enchanted ', false, 120);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('A Midsummer Night’s Dream', false, 121);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Orlando', false, 122);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('30', false, 123);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Neptune and Uranus', true, 124);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Germany', false, 125);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Grace Kelly', false, 126);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Sylvia Plath', false, 127);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('29', false, 128);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Madison', false, 129);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Harper Lee', false, 130);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('potatoes', false, 131);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('rabbit', false, 132);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Elton John', false, 133);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('9', false, 134);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Ad Astra', false, 135);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('9', false, 136);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dr. Cullen', false, 137);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('National Dog Day', false, 138);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('James Irwin', false, 139);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('2', false, 140);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Exodus', false, 141);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Alexander Hamilton', false, 142);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Pocahontas', false, 143);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('vinegar', false, 144);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Dollywood', false, 145);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('money', false, 146);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Philadelphia', true, 147);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Tyler, The Creator', false, 148);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('surfing', true, 149);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('“Anything for you.”', false, 150);
INSERT INTO quiz_manager.answer(answer, correct_answer, question_id) VALUES ('Xbox', false, 151);