INSERT INTO quiz_manager.question(id, question) VALUES(1, 'What is the name for the Jewish New Year?');
INSERT INTO quiz_manager.question(id, question) VALUES(2, 'How many blue stripes are there on the U.S. flag?');
INSERT INTO quiz_manager.question(id, question) VALUES(3, 'Which one of these characters is not friends with Harry Potter?');
INSERT INTO quiz_manager.question(id, question) VALUES(4, 'What is the color of Donald Duck’s bowtie?');
INSERT INTO quiz_manager.question(id, question) VALUES(5, 'What was the name of the band Lionel Richie was a part of?');
INSERT INTO quiz_manager.question(id, question) VALUES(6, 'Which animal does not appear in the Chinese zodiac?');
INSERT INTO quiz_manager.question(id, question) VALUES(7, 'Which country held the 2016 Summer Olympics?');
INSERT INTO quiz_manager.question(id, question) VALUES(8, 'Which planet is the hottest?');
INSERT INTO quiz_manager.question(id, question) VALUES(9, 'Who was the only U.S. President to resign?');
INSERT INTO quiz_manager.question(id, question) VALUES(10, 'What does the “D” in “D-Day” stand for?');
INSERT INTO quiz_manager.question(id, question) VALUES(11, 'In which city can you find the Liberty Bell?');
INSERT INTO quiz_manager.question(id, question) VALUES(12, 'In Pirates of the Caribbean, what was the name of Captain Jack Sparrow’s ship?');
INSERT INTO quiz_manager.question(id, question) VALUES(13, 'According to Forrest Gump, “life was like…”');
INSERT INTO quiz_manager.question(id, question) VALUES(14, 'Linda and Bob from Bob’s Burgers have 3 kids. Which one of these characters is not one of them?');
INSERT INTO quiz_manager.question(id, question) VALUES(15, 'The British band One Direction (rip) was made up of Harry, Louis, Niall, Zayn, and…');
INSERT INTO quiz_manager.question(id, question) VALUES(16, 'What is the rarest blood type?');
INSERT INTO quiz_manager.question(id, question) VALUES(17, 'Holly Golightly is a character in which film?');
INSERT INTO quiz_manager.question(id, question) VALUES(18, 'In The Wizard of Oz, the Tin Man wanted to see the Wizard about getting…');
INSERT INTO quiz_manager.question(id, question) VALUES(19, 'Which U.S. state is known as the sunflower state?');
INSERT INTO quiz_manager.question(id, question) VALUES(20, 'Which one of these characters aren’t a part of the Friends group?');
INSERT INTO quiz_manager.question(id, question) VALUES(21, 'How many bones are there in the human body?');
INSERT INTO quiz_manager.question(id, question) VALUES(22, 'Which famous singer released a song called “Adore You”?');
INSERT INTO quiz_manager.question(id, question) VALUES(23, 'Fe is the chemical symbol for…');
INSERT INTO quiz_manager.question(id, question) VALUES(24, 'How old do you have to be to enter in the hunger games?');
INSERT INTO quiz_manager.question(id, question) VALUES(25, 'What language is the most spoken worldwide?');
INSERT INTO quiz_manager.question(id, question) VALUES(26, 'What year did Barbie come out?');
INSERT INTO quiz_manager.question(id, question) VALUES(27, 'What is Shakespeare’s shortest tragedy?');
INSERT INTO quiz_manager.question(id, question) VALUES(28, 'What is the #1 cookie in the U.S.?');
INSERT INTO quiz_manager.question(id, question) VALUES(29, 'How many hearts does an octopus have?');
INSERT INTO quiz_manager.question(id, question) VALUES(30, 'Who wrote The Scarlett Letter?');
INSERT INTO quiz_manager.question(id, question) VALUES(31, 'Which social media platform came out in 2003?');
INSERT INTO quiz_manager.question(id, question) VALUES(32, 'Which planet in our solar system is the largest?');
INSERT INTO quiz_manager.question(id, question) VALUES(33, 'The Powerpuff Girls are 3 distinct colors. What are they?');
INSERT INTO quiz_manager.question(id, question) VALUES(34, 'Which boyband sings the song “I Want It That Way”?');
INSERT INTO quiz_manager.question(id, question) VALUES(35, 'Who painted the Sistine Chapel ceiling?');
INSERT INTO quiz_manager.question(id, question) VALUES(36, 'In which state did the Salem Witch Trials take place?');
INSERT INTO quiz_manager.question(id, question) VALUES(37, 'Which ocean is the largest?');
INSERT INTO quiz_manager.question(id, question) VALUES(38, 'Which New York City building is the tallest:');
INSERT INTO quiz_manager.question(id, question) VALUES(39, 'What does the “E” in Chuck E. Cheese stand for?');
INSERT INTO quiz_manager.question(id, question) VALUES(40, 'Which country gifted the Statue of Liberty to the U.S.?');
INSERT INTO quiz_manager.question(id, question) VALUES(41, 'Who painted the Mona Lisa?');
INSERT INTO quiz_manager.question(id, question) VALUES(42, 'In which city were Anne Frank and her family in hiding?');
INSERT INTO quiz_manager.question(id, question) VALUES(43, 'There are 4 best friends in the TV show Pretty Little Liars: Hanna, Emily, Aria, and…');
INSERT INTO quiz_manager.question(id, question) VALUES(44, 'In which decade does the Netflix series Stranger Things take place?');
INSERT INTO quiz_manager.question(id, question) VALUES(45, 'Which country consumes the most chocolate?');
INSERT INTO quiz_manager.question(id, question) VALUES(46, 'What is Sodium Chloride?');
INSERT INTO quiz_manager.question(id, question) VALUES(47, 'Which astrological sign is a crab?');
INSERT INTO quiz_manager.question(id, question) VALUES(48, 'In the Bible, how does the Virgin Mary learn of her pregnancy with baby Jesus?');
INSERT INTO quiz_manager.question(id, question) VALUES(49, 'Who, in the Harry Potter series, is Tom Riddle?');
INSERT INTO quiz_manager.question(id, question) VALUES(50, 'The movie The Social Network is about which social media platform:');
INSERT INTO quiz_manager.question(id, question) VALUES(51, 'Who wrote the songs for The Lion King? ');
INSERT INTO quiz_manager.question(id, question) VALUES(52, 'How many daughters does Barack Obama have?');
INSERT INTO quiz_manager.question(id, question) VALUES(53, 'Which Disney princess sings “Just Around The Riverbend”?');
INSERT INTO quiz_manager.question(id, question) VALUES(54, 'Which biblical narrative is connected to Palm Sunday?');
INSERT INTO quiz_manager.question(id, question) VALUES(55, 'In Harry Potter and the Sorcerer’s Stone, who gives Harry the invisibility cloak?');
INSERT INTO quiz_manager.question(id, question) VALUES(56, 'How many burroughs are there in New York City?');
INSERT INTO quiz_manager.question(id, question) VALUES(57, 'In the U.S. version of The Office, Michael Scott burns his foot on:');
INSERT INTO quiz_manager.question(id, question) VALUES(58, 'The superstitution believes that when the groundhog sees his shadow, it means:');
INSERT INTO quiz_manager.question(id, question) VALUES(59, 'What is the longest river in the world?');
INSERT INTO quiz_manager.question(id, question) VALUES(60, 'How many days are in February during a leap year?');
INSERT INTO quiz_manager.question(id, question) VALUES(61, 'How many degrees are in a circle?');
INSERT INTO quiz_manager.question(id, question) VALUES(62, 'Which city is known as the City of Love?');
INSERT INTO quiz_manager.question(id, question) VALUES(63, 'As an adult, how many teeth should you have in your mouth?');
INSERT INTO quiz_manager.question(id, question) VALUES(64, 'What was the name of the boy who won Willy Wonka’s factory?');
INSERT INTO quiz_manager.question(id, question) VALUES(65, 'Edward Scissorhands is known for cutting:');
INSERT INTO quiz_manager.question(id, question) VALUES(66, 'In which city would you find the Fisherman’s Bastion?');
INSERT INTO quiz_manager.question(id, question) VALUES(67, 'Which U.S. president doesn’t/didn’t have a dog in the White House?');
INSERT INTO quiz_manager.question(id, question) VALUES(68, 'What does the “U” stand for in “UFO”?');
INSERT INTO quiz_manager.question(id, question) VALUES(69, 'Which U.S. state is known as “America’s Dairyland”?');
INSERT INTO quiz_manager.question(id, question) VALUES(70, 'Usher found a young boy singing on YouTube and made him into a famous singer. What’s that kid’s name?');
INSERT INTO quiz_manager.question(id, question) VALUES(71, 'Which Olympic sport is Michael Phelps known for?');
INSERT INTO quiz_manager.question(id, question) VALUES(72, 'What is the complementary color of green?');
INSERT INTO quiz_manager.question(id, question) VALUES(73, 'Han Solo is a character from which movie series:');
INSERT INTO quiz_manager.question(id, question) VALUES(74, 'In Men and Black, what are the two FBI agents hunting?');
INSERT INTO quiz_manager.question(id, question) VALUES(75, 'The most recent seasons of American Idol have the judges Katy Perry, Lionel Richie, and…');
INSERT INTO quiz_manager.question(id, question) VALUES(76, 'How many Harry Potter books are there?');
INSERT INTO quiz_manager.question(id, question) VALUES(77, 'What breed is dog is the most popular in the U.S.?');
INSERT INTO quiz_manager.question(id, question) VALUES(78, 'Which rapper was known for his album Blue Slide Park?');
INSERT INTO quiz_manager.question(id, question) VALUES(79, 'How many sides does a hexagon have?');
INSERT INTO quiz_manager.question(id, question) VALUES(80, 'In which city was Ferris Bueller’s Day Off filmed?');
INSERT INTO quiz_manager.question(id, question) VALUES(81, 'The UK is made up of the following countries: England, Ireland, Wales, and…');
INSERT INTO quiz_manager.question(id, question) VALUES(82, 'How many elements are there on the periodic table?');
INSERT INTO quiz_manager.question(id, question) VALUES(83, 'Where is the United Nations Headquarters?');
INSERT INTO quiz_manager.question(id, question) VALUES(84, 'What famous singer sings with Taylor Swift in her song “Me!”?');
INSERT INTO quiz_manager.question(id, question) VALUES(85, 'In what year did women get the right to vote?');
INSERT INTO quiz_manager.question(id, question) VALUES(86, 'Where in the United States is the largest aquarium?');
INSERT INTO quiz_manager.question(id, question) VALUES(87, 'There are 5 great lakes in the United States: Lake Michigan, Lake Superior, Lake Ontario, Lake Erie, and…');
INSERT INTO quiz_manager.question(id, question) VALUES(88, 'Neil Armstrong was the first man…');
INSERT INTO quiz_manager.question(id, question) VALUES(89, 'What does “FBI” stand for?');
INSERT INTO quiz_manager.question(id, question) VALUES(90, 'What is the deadliest snake?');
INSERT INTO quiz_manager.question(id, question) VALUES(91, 'In The Office, what object of Dwight’s does Jim put in jello?');
INSERT INTO quiz_manager.question(id, question) VALUES(92, 'In Friends, how many times has Ross been married?');
INSERT INTO quiz_manager.question(id, question) VALUES(93, 'What is a group of lions called?');
INSERT INTO quiz_manager.question(id, question) VALUES(94, 'How many keys are on a piano?');
INSERT INTO quiz_manager.question(id, question) VALUES(95, 'What was the name of the Greek mythological woman who had snakes for hair?');
INSERT INTO quiz_manager.question(id, question) VALUES(96, 'What do you call a baby goat?');
INSERT INTO quiz_manager.question(id, question) VALUES(97, 'According to Phineas and Ferb, there are __ days of summer vacation?');
INSERT INTO quiz_manager.question(id, question) VALUES(98, 'What is the most populous city in Canada?');
INSERT INTO quiz_manager.question(id, question) VALUES(99, 'The Da Vinci Code opens with a murder in which museum:');
INSERT INTO quiz_manager.question(id, question) VALUES(100, 'From which TV show is the family of Roses: Johnny, Moira, David, and Alexis?');
INSERT INTO quiz_manager.question(id, question) VALUES(101, 'After The Simpsons, what is the longest running TV show?');
INSERT INTO quiz_manager.question(id, question) VALUES(102, 'Which Disney princess sings “A Dream Is A Wish Your Heart Makes”?');
INSERT INTO quiz_manager.question(id, question) VALUES(103, 'How often does the moon orbit the Earth?');
INSERT INTO quiz_manager.question(id, question) VALUES(104, 'In Greek Mythology, who is the Queen of the Underworld?');
INSERT INTO quiz_manager.question(id, question) VALUES(105, 'How many points are a touchdown worth?');
INSERT INTO quiz_manager.question(id, question) VALUES(106, 'How many feet are in a mile?');
INSERT INTO quiz_manager.question(id, question) VALUES(107, 'Where is the Oval Office located in the White House?');
INSERT INTO quiz_manager.question(id, question) VALUES(108, 'At what temperature (Fahrenheit) does water freeze at?');
INSERT INTO quiz_manager.question(id, question) VALUES(109, 'Where in Pennsylvania is The Office based?');
INSERT INTO quiz_manager.question(id, question) VALUES(110, 'In the movie Good Will Hunting, which college does Skylar attend?');
INSERT INTO quiz_manager.question(id, question) VALUES(111, 'Where in California is Disneyland located?');
INSERT INTO quiz_manager.question(id, question) VALUES(112, '“I see dead people,” is a line from which horror film…');
INSERT INTO quiz_manager.question(id, question) VALUES(113, 'Who founded Microsoft?');
INSERT INTO quiz_manager.question(id, question) VALUES(114, 'In which city was the movie National Treasure filmed?');
INSERT INTO quiz_manager.question(id, question) VALUES(115, 'Which classic novel has the line “Stay Gold, Ponyboy”?');
INSERT INTO quiz_manager.question(id, question) VALUES(116, 'What was the name of Harry Potter’s pet owl?');
INSERT INTO quiz_manager.question(id, question) VALUES(117, 'Which Disney princess had 3 fairy godmothers?');
INSERT INTO quiz_manager.question(id, question) VALUES(118, 'Which band came back together in 2019?');
INSERT INTO quiz_manager.question(id, question) VALUES(119, 'Steve Jobs is known for wearing a black…');
INSERT INTO quiz_manager.question(id, question) VALUES(120, 'In which movie does Anne Hathaway play a poor, homeless woman?');
INSERT INTO quiz_manager.question(id, question) VALUES(121, 'The movie 10 Things I Hate About You was based on which play by Shakespeare:');
INSERT INTO quiz_manager.question(id, question) VALUES(122, 'Where does Nathan’s Hot Dog Eating Contest take place?');
INSERT INTO quiz_manager.question(id, question) VALUES(123, 'What age did Amy Winehouse, Janis Joplin, and Jimi Hendrix die?');
INSERT INTO quiz_manager.question(id, question) VALUES(124, 'Which two planets in our solar system are known as “ice giants”?');
INSERT INTO quiz_manager.question(id, question) VALUES(125, 'What country is Prague in?');
INSERT INTO quiz_manager.question(id, question) VALUES(126, 'What is the name of the actress in Funny Face, Sabrina and Roman Holiday?');
INSERT INTO quiz_manager.question(id, question) VALUES(127, 'Which poet wrote the poem “The Raven”? ');
INSERT INTO quiz_manager.question(id, question) VALUES(128, 'How many ribs are in the human body?');
INSERT INTO quiz_manager.question(id, question) VALUES(129, 'Who was the 16th president of the United States?');
INSERT INTO quiz_manager.question(id, question) VALUES(130, 'Who wrote the novel Slaughterhouse-Five?');
INSERT INTO quiz_manager.question(id, question) VALUES(131, 'In The Office, what was the food that Dwight grew on his farm?');
INSERT INTO quiz_manager.question(id, question) VALUES(132, 'What animal is associated with ancient Egypt?');
INSERT INTO quiz_manager.question(id, question) VALUES(133, 'In 2016, a musician won the Nobel Peace Prize for Literature. Who was it?');
INSERT INTO quiz_manager.question(id, question) VALUES(134, 'How many time zones are there in the world?');
INSERT INTO quiz_manager.question(id, question) VALUES(135, 'What was the name of the movie that featured Matthew McConaughey, Michael Caine, Anne Hathaway, John Lithgow, and Matt Damon?');
INSERT INTO quiz_manager.question(id, question) VALUES(136, 'How many rings are there in the Olympic symbol?');
INSERT INTO quiz_manager.question(id, question) VALUES(137, 'Twilight was both a book and a movie, with the main character Bella Swan being pulled into two different love directions with Edward Cullen and….');
INSERT INTO quiz_manager.question(id, question) VALUES(138, 'What is celebrated on December 26th?');
INSERT INTO quiz_manager.question(id, question) VALUES(139, 'What is the name of the second American astronaut to step foot on the moon?');
INSERT INTO quiz_manager.question(id, question) VALUES(140, 'How many eyes does a spider have?');
INSERT INTO quiz_manager.question(id, question) VALUES(141, 'What is the first book of the Old Testament in the Bible?');
INSERT INTO quiz_manager.question(id, question) VALUES(142, 'Which founding father is known for his large handwriting on the Declaration of Independence?');
INSERT INTO quiz_manager.question(id, question) VALUES(143, 'What was the first Disney film that was produced in color?');
INSERT INTO quiz_manager.question(id, question) VALUES(144, 'Sodium bicarbonate is used in the kitchen as what?');
INSERT INTO quiz_manager.question(id, question) VALUES(145, 'In the 1983 movie National Lampoon’s Vacation, what is the name of the fictional amusement park the Griswold family is trying to go to?');
INSERT INTO quiz_manager.question(id, question) VALUES(146, 'In Ray Bradbury’s novel Farenheit 451, what are they burning?');
INSERT INTO quiz_manager.question(id, question) VALUES(147, 'What was the first capital of the United States?');
INSERT INTO quiz_manager.question(id, question) VALUES(148, 'Which actor performs music under the stage name Childish Gambino?');
INSERT INTO quiz_manager.question(id, question) VALUES(149, 'Which water sport is the official sport for the state of Hawaii?');
INSERT INTO quiz_manager.question(id, question) VALUES(150, 'In the movie The Princess Bride, what is Westley’s response to the requests of Buttercup?');
INSERT INTO quiz_manager.question(id, question) VALUES(151, 'What is the name of the company that published the Mario Kart video game?');
INSERT INTO quiz_manager.question(id, question) VALUES(152, 'Will this work?');